env:
  browser: false
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  indent:
      - warn
      - 2
  linebreak-style:
      - error
      - unix
  quotes:
      - warn
      - single
  semi:
      - warn
      - always
  no-unused-vars:
      - warn
      - args: none
  no-console: off
  curly: error
  eqeqeq: error
  no-throw-literal: error
  strict: error
  no-var: error
  dot-notation: error
  no-tabs: error
  no-trailing-spaces: warn
  # no-use-before-define: error
  "@typescript-eslint/no-explicit-any": warn
  "@typescript-eslint/no-unused-vars": warn
  no-useless-call: error
  no-with: error
  operator-linebreak: error
  # require-jsdoc:
  #     - error
  #     - require:
  #         ClassDeclaration: true
  #         MethodDefinition: true
  #         FunctionDeclaration: true
  # valid-jsdoc:
  #     - error
  #     - requireReturn: false
  # yoda: error

